name: 'Jellyfin Plugin'

on:
  push:
    branches-ignore:
      - release

permissions:
  contents: write

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Patch version
        run: sed -i "/Version/s/.0</.$GITHUB_RUN_NUMBER</" Directory.Build.props
      - name: Setup .NET 8.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8
      - name: Restore NuGet Packages
        run: dotnet restore
      - name: .NET Test
        run: dotnet test --configuration Release Jellyfin.Plugin.Bangumi.Test
      - name: .NET Publish
        run: dotnet publish --configuration Release --output publish Jellyfin.Plugin.Bangumi
      - name: .NET Publish (Emby)
        run: dotnet publish --configuration Release --output publish Emby.Plugin.Bangumi
      - name: Upload to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: "${{ github.token }}"
          tag: ci
          prerelease: true
          overwrite: true
          file_glob: true
          file: publish/*.Plugin.Bangumi.dll
